[package]
name = "lc3-assembler"
version = "0.1.0"
edition = "2021"

[[bin]]
name = "lc3-assembler"
path = "src/assembler.rs"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
